name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache SonarQube packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=<VotreProjectKey>
          -Dsonar.organization=<VotreOrganisation> # Seulement pour SonarCloud
          -Dsonar.host.url=<URLDuServeurSonarQube> # URL du serveur SonarQube, supprimez cette ligne si vous utilisez SonarCloud
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
